#!/bin/bash
# Quick icon generation guide
# This script documents the steps needed to generate rocket icons

echo "🚀 Astro Spotted Icon Generation Guide"
echo "======================================"
echo ""
echo "The rocket icon SVG template is ready at:"
echo "  extension/public/rocket-icon.svg"
echo ""
echo "Choose ONE of these methods to generate PNG icons:"
echo ""
echo "METHOD 1: Online Converter (Fastest - 5 minutes)"
echo "───────────────────────────────────────────────"
echo "1. Visit: https://convertio.co/svg-png/"
echo "2. Upload: extension/public/rocket-icon.svg"
echo "3. Download the 256×256 PNG"
echo "4. Use an online image resizer to create sizes:"
echo "   - 16×16, 19×19, 32×32, 38×38, 128×128"
echo "5. Place all PNG files in: extension/public/"
echo ""
echo "METHOD 2: Using Node Canvas (Automated - 10 minutes)"
echo "────────────────────────────────────────────────────"
echo "1. cd extension"
echo "2. npm install --save-dev canvas"
echo "3. npm run gen:icons"
echo "4. Done! All icons will be generated automatically"
echo ""
echo "METHOD 3: Using Inkscape (Professional - 15 minutes)"
echo "──────────────────────────────────────────────────────"
echo "1. Install Inkscape: https://inkscape.org/release/"
echo "2. Open: extension/public/rocket-icon.svg"
echo "3. File → Export As → image.png"
echo "4. Change size to each required dimension"
echo "5. Repeat for all 14 icons needed"
echo ""
echo "FILES NEEDED (14 total):"
echo "───────────────────────"
echo "Icon sizes:"
echo "  ✓ icon-16.png"
echo "  ✓ icon-19.png" 
echo "  ✓ icon-32.png"
echo "  ✓ icon-38.png"
echo "  ✓ icon-128.png"
echo "  ✓ icon-256.png"
echo "  ✓ icon-128-nopadding.png"
echo "  ✓ icon-256-nopadding.png"
echo ""
echo "Action icons (inactive - gray):"
echo "  ✓ action-inactive-16.png"
echo "  ✓ action-inactive-19.png"
echo "  ✓ action-inactive-32.png"
echo "  ✓ action-inactive-38.png"
echo ""
echo "Action icons (active - colored):"
echo "  ✓ action-active-16.png"
echo "  ✓ action-active-19.png"
echo "  ✓ action-active-32.png"
echo "  ✓ action-active-38.png"
echo ""
echo "VERIFICATION:"
echo "─────────────"
echo "After icons are ready, run:"
echo "  cd extension"
echo "  yarn build"
echo "  yarn build:chrome  # or build:firefox, build:safari"
echo ""
echo "Load the extension in dev mode and test on:"
echo "  - https://astro.build"
echo "  - https://github.com/withastro"
echo "  - Any other Astro-powered website"
echo ""
echo "📖 For detailed instructions, see: ICON_SETUP.md"
echo ""
